base_model: google/gemma-3-4b-it

# LoRA
r: 16
lora_alpha: 32
lora_dropout: 0.1
bias: none
target_modules: 
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - up_proj
  - down_proj
  - gate_proj


# SFT
max_seq_length: 4096
num_train_epochs: 5
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 3.0e-5
warmup_ratio: 0.05
weight_decay: 0.0
logging_steps: 5
save_steps: 50

# Precision / Optim
bf16: true      # 안 되면 train.py에서 fp16로 자동 폴백
fp16: false
optim: paged_adamw_8bit

output_dir: outputs/gemma3-4b-it-lora
